# Generated by Django 3.2.25 on 2025-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_labtestbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='upcoming', max_length=20),
        ),
    ]
