# Generated by Django 5.2 on 2025-05-05 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_is_paid_appointment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtestbooking',
            old_name='test_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='labtestbooking',
            old_name='time_slot',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='labtestbooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='labtestbooking',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='preferred_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
    ]
